dist: trusty
sudo: true

matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd backend
      script:
        - ./gradlew build
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend
        - npm install
      script:
        - npm run build