dist: trusty
sudo: required

matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd backend
      script:
        - ./gradlew build
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend
      script:
        - ng build --prod --aot