dist: trusty
sudo: required

matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd backend
      script:
        - ls -l gradle/wrapper
        - ./gradlew build
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend
      script:
        - npm run lint
        - npm run test
        - npm run build