dist: trusty
sudo: false

matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd backend
      script:
        - pwd
        - ./gradlew build
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend
      script:
        - npm run build