dist: trusty
sudo: required

branches:
  only:
  - master

matrix:
  include:
    - language: java
      jdk: oraclejdk10
      before_script:
        - cd backend
      script:
        - ./gradlew build
    - language: node_js
      node_js:
        - node
      addons:
        chrome: stable
      before_script:
        - cd frontend
        - npm install
      script:
        - npm run lint
        - npm run test-travis-ci
        # - npm run e2e
        - npm run build --prod --aot